yasno:
  city_id: 25
  dso_id: 902
  group_id: "5.2"
  local_tz: "Europe/Kyiv"
  url: "https://app.yasno.ua/api/blackout-service/public/shutdowns/regions/{city_id}/dsos/{dso_id}/planned-outages"

storage:
  type: file_storage
  path: !ENV ${FILE_PATH:./outages}

notifier:
  type: telegram
  bot_token: !ENV ${TELEGRAM_BOT_TOKEN}
  chat_id: !ENV ${TELEGRAM_CHAT_ID}
  thread_id: !ENV ${TELEGRAM_THREAD_ID}