yasno:
  city_id: 25
  dso_id: 902
  group_id: "5.2"
  local_tz: "Europe/Kyiv"
  url: "https://app.yasno.ua/api/blackout-service/public/shutdowns/regions/{city_id}/dsos/{dso_id}/planned-outages"

db:
  host: !ENV ${DB_HOST:127.0.0.1}
  port: !ENV ${DB_PORT:33060}
  user: !ENV ${DB_USER:yasno}
  password: !ENV ${DB_PASSWORD:yasno_password}
  database: !ENV ${DB_NAME:outages}

notifier:
  type: telegram
  bot_token: !ENV ${TELEGRAM_BOT_TOKEN}
  chat_id: !ENV ${TELEGRAM_CHAT_ID}