name: Lint and test
on:
  push:
    branches:
      - main
      - feature-*

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Show files
      run: ls -l 
    - name: ruff-action
      uses: astral-sh/ruff-action@v3.5.1