name: Lint and test
on:
  push:
    branches:
      - main
      - feature-*

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.13"]
    steps:
    - name: Print GITHUB_WORKSPACE
      run: echo $GITHUB_WORKSPACE
    - name: Show files
      run: ls -l ../
    - name: ruff-action
      uses: astral-sh/ruff-action@v3.5.1
      with:
        src: >-
          "./src"
          "./main.py"
          "./tests"
